# Generated by Django 6.1 on 2026-10-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='fas fa-mosque', help_text="FontAwesome icon class e.g. 'fas fa-book-quran'", max_length=64)),
                ('capacity', models.CharField(blank=True, help_text='e.g. 2,500 Worshipers', max_length=64)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Mosque Facility',
                'verbose_name_plural': 'Mosque Facilities',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Al-Firdaus Digital Center', max_length=128)),
                ('phone', models.CharField(default='+255 700 000 000', max_length=32)),
                ('email', models.EmailField(default='info@al-firdaus.org', max_length=254)),
                ('address', models.CharField(default='Kijitonyama, Dar es Salaam, Tanzania', max_length=255)),
                ('about_text', models.TextField(default='Al-Firdaus Digital Platform offers comprehensive Islamic services, prayer schedules, institute education, khutbah archives, and community support.')),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com')),
                ('youtube_url', models.URLField(blank=True, default='https://youtube.com')),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SiteStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. Daily Worshipers', max_length=128)),
                ('value', models.CharField(help_text='e.g. 2,500+', max_length=64)),
                ('icon', models.CharField(default='fas fa-users', max_length=64)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Site & Impact Stat',
                'verbose_name_plural': 'Site & Impact Stats',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('title', models.CharField(help_text='e.g. Chief Imam, Resident Scholar, Quran Instructor', max_length=128)),
                ('bio', models.TextField(blank=True)),
                ('photo_url', models.CharField(blank=True, help_text='URL of teacher photo or leave empty for default avatar', max_length=512)),
                ('specialty', models.CharField(default='Islamic Studies & Quran', max_length=128)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Teacher / Imam',
                'verbose_name_plural': 'Teachers & Imams',
                'ordering': ['order', 'name'],
            },
        ),
    ]
