# Generated by Django 6.1 on 2026-09-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('hijri_date', models.CharField(blank=True, max_length=128)),
                ('fajr', models.CharField(max_length=16)),
                ('sunrise', models.CharField(max_length=16)),
                ('dhuhr', models.CharField(max_length=16)),
                ('asr', models.CharField(max_length=16)),
                ('maghrib', models.CharField(max_length=16)),
                ('isha', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name': 'Prayer Time',
                'verbose_name_plural': 'Prayer Times',
                'ordering': ['date'],
            },
        ),
    ]
