# Generated by Django 6.1 on 2026-10-03 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('quran', 'Quran & Tajweed'), ('arabic', 'Arabic Language'), ('islamic_studies', 'Islamic Studies'), ('hifdh', 'Hifdh Program')], default='quran', max_length=32)),
                ('description', models.TextField()),
                ('age_group', models.CharField(default='All Ages', max_length=64)),
                ('schedule', models.CharField(blank=True, max_length=128)),
                ('instructor', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_featured', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('contacted', 'Contacted'), ('enrolled', 'Enrolled')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='institute.course')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
